---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: nginx
    newTag: 1.23-alpine

namespace: test-nginx
namePrefix: test-
commonLabels:
  app: test-nginx

resources:
  - ../../base

configMapGenerator:
  - name: someconfigmap
    files:
      - configs/configMap

patchesStrategicMerge:
  - vars.yaml
  - limits.yaml

patches:
  - patch: |-
      - op: replace
        path: /metadata/labels/kubernetes.io~1metadata.name
        value: test-nginx
    target:
      kind: Namespace
